### ISSUE TITLE
Error: Unknown option given. First argument must be the option internal id or the option name. You can use the Curl.option constants.

### ISSUE THREAD

**Issue by ijshah** [do-web/curl-request#1]
-------------------------------------------------detail error -----------------------------------
Error: Unknown option given. First argument must be the option internal id or the option name. You can use the Curl.option constants.
    at Error (native)
    at Curl.setOpt (/home/js2/Version2/node_modules/node-libcurl/lib/Curl.js:1004:15)
    at module.exports.setOpt (/home/js2/Version2/node_modules/curl-request/index.js:39:19)
    at /home/js2/Version2/routes/routes.js:3262:22
    at /home/js2/Version2/node_modules/mongoose/lib/query.js:2323:18
    at process._tickCallback (internal/process/next_tick.js:103:7)

how to pass setOpt  `option?

`const curl = require('curl-request');
var param = {
                    'device_id': 2325, // Device ID
                    'module_id': 'dm_bandwidth', // Module ID or name
                    'period': 'week'
  };
  var opt = [];
  opt = [{'httpheader': 'Content-type: application/json'},{'userpwd':'password'},
{'Curl.option.useragent': 'Ubersmith API Client PHP/1.0'}];
var url = 'https://support.privatelayer.com/api/2.0/?method=device.module_graph';
curl.setHeaders([
'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36',
'Accept-Encoding: gzip',
                    'Expect:',
                ])
                curl.setOpt(opt)
                    .setBody(param)
                    .get(url)
                    .then(({ statusCode, body, headers }) => {
                        console.log("curl", statusCode, "body", body, "header", headers)

                        res.json({ success: true, deviceDetail: getDeviceDetail[0], devicegraph: body });
                    })
                    .catch((e) => {
                        console.log(e);
                    });`

**Comment by do-web** [comment]
Why you want so set setOpt? There is no setOpt command here. If you want to access the node-libcurl setOpt command you must use curl.curl.setOpt('FOLLOWLOCATION', true);

Please look at the examples in the Readme. You want to set the headers, so please use the setHeaders method.

`
curl.setHeaders([
    'Content-type: application/json',
    'userpwd: password',
 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36',
])
`

**Comment by apoorva-shah** [comment]
Hello @do-web 
I want to pass gzip: true in request.
Can you please guide?

Thanks in advance.
