### ISSUE TITLE
How to use curl resolve option with this library?

### ISSUE THREAD

**Issue by PragmaticEd** [do-web/curl-request#8]
Curl has option [resolve](https://support.acquia.com/hc/en-us/articles/360005257154-Use-cURL-s-resolve-option-to-pin-a-request-to-an-IP-address)

How does one use this here, so we don't have to change hosts file?

**Comment by do-web** [comment]
Please look here: 

``https://github.com/JCMais/node-libcurl/tree/develop/examples``

Use this options like this:

```curl.libcurl.setOpt()```
